#!/usr/bin/env node
// Generates the Android string tables from the web app's translations, so the
// two apps share one source of truth. Run after editing
// src/i18n/translations.ts:
//
//   node android/scripts/gen-i18n.mjs
//
// Needs Node 23.6+ (it imports the TypeScript file directly).
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const source = resolve(root, 'src/i18n/translations.ts');
const target = resolve(root, 'android/app/src/main/java/io/github/corum86/vacationmap/i18n/Translations.kt');

const { translations } = await import(pathToFileURL(source).href);

// strings that name the browser or the web build's configuration
const overrides = {
  en: {
    'data.hint': 'Edits save to this device only — export data to back up.',
    'ai.unavailable': 'AI search unavailable — this build has no Gemini API key (see android/README.md).',
    'sync.status.outdated': 'Saved by a newer version of the app — update the app to keep syncing',
  },
  el: {
    'data.hint': 'Οι αλλαγές αποθηκεύονται μόνο σε αυτή τη συσκευή — κάντε εξαγωγή για αντίγραφο ασφαλείας.',
    'ai.unavailable':
      'Η αναζήτηση AI δεν είναι διαθέσιμη — αυτή η έκδοση δεν έχει κλειδί Gemini API (δείτε το android/README.md).',
    'sync.status.outdated':
      'Αποθηκεύτηκε από νεότερη έκδοση της εφαρμογής — ενημερώστε την εφαρμογή για να συνεχιστεί ο συγχρονισμός',
  },
};

function kotlinString(text) {
  return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/\n/g, '\\n')}"`;
}

function table(lang) {
  const entries = Object.entries({ ...translations[lang], ...overrides[lang] });
  return entries.map(([key, text]) => `        ${kotlinString(key)} to ${kotlinString(text)},`).join('\n');
}

const keys = Object.keys(translations.en);
for (const lang of Object.keys(translations)) {
  const missing = keys.filter((key) => !(key in translations[lang]));
  if (missing.length > 0) throw new Error(`${lang} lacks: ${missing.join(', ')}`);
}

writeFileSync(
  target,
  `// GENERATED by android/scripts/gen-i18n.mjs from src/i18n/translations.ts — do not edit.
package io.github.corum86.vacationmap.i18n

internal object Translations {
    val en: Map<String, String> = mapOf(
${table('en')}
    )

    val el: Map<String, String> = mapOf(
${table('el')}
    )
}
`,
);
console.log(`Wrote ${keys.length} keys × ${Object.keys(translations).length} languages to ${target}`);
